on:
  pull_request:
    branches:
      - master
      - 'fix/schema-defs'
name: Pull request workflow
jobs:
  validate_nodes:
    name: Validate nodes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate nodes schema
        uses: Adzz/jest_test_action@v1.0.0
        with:
          command: validate --ignore-engines
