on:
  pull_request:
    branches:
      - master
name: Pull request workflow
jobs:
  validate_nodes:
    name: Validate nodes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate nodes schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./node.schema.json
          json_path_pattern: ^configs\/.*(\.json)$
