on:
  pull_request:
    branches:
      - master
name: Pull request workflow
jobs:
  validate_nodes:
    name: Validate nodes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
              
      - name: Set Node-js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'

      - name: Install Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install --ignore-engines # will run `yarn install` command

      - name: Validate nodes schema
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: validate # validate using json schema
          
      - name: Test appBuild and ids
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: check-entries # perform other validations
